#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Exit if fzf is not installed
if ! builtin type fzf >/dev/null 2>&1; then
  print "fzf not installed, exiting"
fi

export FZF_CTRL_R_OPTS="--height=15"
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh

alias config="/usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME"

qotd
